name: aura_music
description: "A new Flutter project."
publish_to: 'none'
version: 2.0.0+1

environment:
  sdk: ^3.10.1

dependencies:
  flutter:
    sdk: flutter
  youtube_explode_dart: ^2.2.1
  just_audio: ^0.9.40
  audio_service: ^0.18.15
  flutter_riverpod: ^2.5.1
  go_router: ^14.6.2
  cached_network_image: ^3.4.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  intl: ^0.19.0
  http: ^1.2.2
  dio: ^5.7.0
  shared_preferences: ^2.2.2
  package_info_plus: ^8.0.0
  permission_handler: ^11.3.1
  path_provider: ^2.1.4
  open_file: ^3.5.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
